In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
Yes, there is a difference in the data type of the list_ variable and the array_list variable. The list_ variable is a Python list, while the array_list variable is a numpy array.

In [3]:
import numpy as np

list_ = ['1','2','3','4','5']
array_list = np.array (object = list_)

print("Data type of list_:",type(list_))
print("Data type of array_list:",type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
import numpy as np

# Your existing code
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

#print data types
for item in list_:
    print(f"Types of element in list_:{type(item).__name__}")
    
for item in array_list:
    print(f"Type of element in array_list:{type(item).__name__}")

Types of element in list_:str
Types of element in list_:str
Types of element in list_:str
Types of element in list_:str
Types of element in list_:str
Type of element in array_list:str_
Type of element in array_list:str_
Type of element in array_list:str_
Type of element in array_list:str_
Type of element in array_list:str_


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [ ]:
Lists:
A list is an inbuilt collection of items that can contain elements of multiple data types (numeric, character, logical values, etc.).
Lists are ordered and support negative indexing.

In [5]:
sample_list = [1, "Yash", ['a', 'e']]
print(type(sample_list))  


<class 'list'>


In [ ]:
Arrays:
An array is a vector containing homogeneous elements (belonging to the same data type).
Elements in arrays are allocated contiguous memory locations.
Unlike lists, arrays require all elements to be of the same data type (typically numeric types like integers or floats).

In [6]:
import array as arr
a = arr.array('i', [1, 2, 3])
print(type(a))  


<class 'array.array'>


In [ ]:
Difference Between List and Array:
Lists can consist of elements belonging to different data types, while arrays only consist of elements belonging to the same data type.
Lists do not require explicit module import for declaration, whereas arrays need the array module.
Lists can handle arithmetic operations directly, but arrays are more memory-efficient due to their contiguous memory allocation.

In [7]:
import numpy as np

# Assuming list_ is defined somewhere before
# list_ = [1, 2, 3, 4, 5]

array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types in list_:")
for item in list_:
    print(type(item))

# Print data types of elements in array_list
print("\nData types in array_list:")
for item in array_list:
    print(type(item))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [ ]:
1.Shape: The shape of an array refers to its dimensions. For a 2D array, it represents the number of rows and columns. You can obtain the shape using the .shape attribute. In this case, num_array.shape will give you the shape
2.Size: The size of an array is the total number of elements in it. You can get the size using the .size attribute. For num_array, num_array.size will give you the size.

In [9]:
import numpy as np

#your existing code to create num_array
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object = num_list)

#Characteristics
shape = num_array.shape
size = num_array.size
print(f"Shape of num_array:{shape}")
print(f"Size of num_array:{size}")

Shape of num_array:(2, 3)
Size of num_array:6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [11]:
import numpy as np

#create a 3*3 array of zeros
zero_matrix = np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [12]:
import numpy as np

#Create a 5*5 identity matrix
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
